import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import './../register-web-components';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <core-test />
      {/* <div className={styles.main}>Module css Test </div> */}
      <h1 className="text-3xl btn font-bold underline">Hello NextJS!</h1>
    </div>
  );
};

export default Home;
